<div id="tree"></div>
<div id="tree22">
    <ul id="ft-id-1" class="ui-fancytree fancytree-container fancytree-plain" tabindex="0" role="tree" aria-multiselectable="true" aria-activedescendant="ui-id-2">
        <li role="treeitem" aria-expanded="true" aria-selected="false" id="ui-id-1" class=""><span class="fancytree-node fancytree-expanded fancytree-folder fancytree-has-children fancytree-exp-e fancytree-ico-ef"><span role="button" class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">Books</span></span>
            <ul role="group" style="">
                <li role="treeitem" aria-selected="false"><span class="fancytree-node fancytree-exp-n fancytree-ico-c"><span class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">Art of War</span></span></li>
                <li role="treeitem" aria-selected="false"><span class="fancytree-node fancytree-exp-n fancytree-ico-c"><span class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">The Hobbit</span></span></li>
                <li role="treeitem" aria-selected="false"><span class="fancytree-node fancytree-exp-n fancytree-ico-c"><span class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">The Little Prince</span></span></li>
                <li role="treeitem" aria-selected="false" class="fancytree-lastsib"><span class="fancytree-node fancytree-lastsib fancytree-exp-nl fancytree-ico-c"><span class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">Don Quixote</span></span></li>
            </ul>
        <li role="treeitem" aria-expanded="false" aria-selected="false"><span class="fancytree-node fancytree-folder fancytree-has-children fancytree-exp-c fancytree-ico-cf"><span role="button" class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">Music</span></span></li>
        <li role="treeitem" aria-expanded="true" aria-selected="false" id="ui-id-2"><span class="fancytree-node fancytree-expanded fancytree-folder fancytree-has-children fancytree-exp-e fancytree-ico-ef"><span role="button" class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">Electronics &amp; Computers</span></span>
            <ul role="group">
                <li role="treeitem" aria-expanded="false" aria-selected="false"><span class="fancytree-node fancytree-folder fancytree-has-children fancytree-exp-c fancytree-ico-cf"><span role="button" class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">Cell Phones</span></span></li>
                <li role="treeitem" aria-expanded="false" aria-selected="false" class="fancytree-lastsib"><span class="fancytree-node fancytree-folder fancytree-has-children fancytree-lastsib fancytree-exp-cl fancytree-ico-cf"><span role="button" class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">Computers</span></span></li>
            </ul>
        </li>
        <li role="treeitem" aria-expanded="false" aria-selected="false" class="fancytree-lastsib"><span class="fancytree-node fancytree-folder fancytree-has-children fancytree-lastsib fancytree-lazy fancytree-exp-cdl fancytree-ico-cf"><span role="button" class="fancytree-expander"></span><span role="checkbox" class="fancytree-checkbox"></span><span role="presentation" class="fancytree-icon"></span><span class="fancytree-title">More...</span></span></li>
    </ul>
</div>